set(POLICY_CONVERT_RELATIVE_PATHS_TO_ABSOLUTE CMP0076)
set(POLICY_ALLOW_LINK_LIBRARIES_IN_OTHER_DIRECTORIES CMP0079)
set(POLICY_OPTION_HONORS_NORMAL_VARIABLES CMP0077)


function(trg_setup_required_cmake_policies) 
    if(POLICY ${POLICY_OPTION_HONORS_NORMAL_VARIABLES})
	    cmake_policy(SET ${POLICY_OPTION_HONORS_NORMAL_VARIABLES} NEW)
        message("[INFO] Policy {POLICY_OPTION_HONORS_NORMAL_VARIABLES} set to NEW")
    endif()

    if(POLICY ${POLICY_CONVERT_RELATIVE_PATHS_TO_ABSOLUTE})
        cmake_policy(SET ${POLICY_CONVERT_RELATIVE_PATHS_TO_ABSOLUTE} NEW)
        message("[INFO] Policy {POLICY_CONVERT_RELATIVE_PATHS_TO_ABSOLUTE} set to NEW")
    endif()

    if(POLICY ${POLICY_ALLOW_LINK_LIBRARIES_IN_OTHER_DIRECTORIES})
        cmake_policy(SET ${POLICY_ALLOW_LINK_LIBRARIES_IN_OTHER_DIRECTORIES} NEW)
        message("[INFO] Policy {POLICY_ALLOW_LINK_LIBRARIES_IN_OTHER_DIRECTORIES} set to NEW")
    endif()
endfunction()